Implementation of Auth Management app
talhaw/AuthManager pull request #1
Opened 2019-11-05 09:50 UTC by talhaw

2019-11-06 19:35 UTC, ahab94 requested changes

2019-11-06 19:35 UTC, ahab94 commented on test.py
> +from flask import Flask
Why are we keeping routes in test.py?

2019-11-06 19:35 UTC, ahab94 commented on .gitignore
> +__pycache__
Add line ending..

2019-11-06 19:35 UTC, ahab94 commented on utils/utils.py
> +import traceback
Queries should not be in utils...
Make a sep package for db.
It should have a class named "db" or "client"..
It should have queries to add/delete/get Session.

Use those in routes.

2019-11-07 09:33 UTC, ahab94 commented on db/client.py
> +            if AuthManager.objects(user_id=username):
Session should not have conflict... A user can sign in from multiple things.

2019-11-07 09:34 UTC, ahab94 commented on db/client.py
> +
This should be a class right? As i commented earlier....

2019-11-07 09:34 UTC, ahab94 commented on .gitignore
> +__pycache__
This is still unresolved.

2019-11-07 09:35 UTC, ahab94 commented on db/client.py
> +            if AuthManager.objects(user_id=username):
BTW... what is `AuthManager`?

2019-11-07 09:35 UTC, ahab94 commented on main/main.py
> +            elif status == 409:
Don't handle this case.

2019-11-07 09:36 UTC, ahab94 commented on main/main.py
> +            elif status == 404:
this should be 401

2019-11-07 09:37 UTC, ahab94 commented on utils/utils.py
> +import traceback
Why do we still have this?

2019-11-07 09:38 UTC, talhaw commented on db/client.py
> +            if AuthManager.objects(user_id=username):
Its the name of model (database structure)

2019-11-07 09:38 UTC, ahab94 commented on utils/utils.py
> +def add_data_to_database(username, password):
You are still using this function...

2019-11-07 09:39 UTC, ahab94 commented on db/client.py
> +        if (
What is this doing?

2019-11-07 09:40 UTC, talhaw commented on utils/utils.py
> +def add_data_to_database(username, password):
This function will be call from main. Which will will then call the add_session

2019-11-07 09:41 UTC, ahab94 commented on models/models.py
> +def new_client():
connect should not happen here... as we want to create a sep class for client... A client should have a constructor which takes these values that connect uses.
And the queries should be part of that class..

2019-11-07 09:49 UTC, talhaw commented on db/client.py
> +        if (
It will call new_client to establish connection. Then will make the session if the credentials are right

2019-11-07 09:51 UTC, talhaw commented on models/models.py
> +def new_client():
okkk

2019-11-07 11:12 UTC, ahab94 commented on db/client.py
> +        if (
In this fashion `new_client` will create a new connection on every api call. Over time it will consume all cpu and memory because of these leaking connections.. Do something like `Runtime` that we did in ApnaSchool.

2019-11-07 11:12 UTC, ahab94 commented on utils/service.py
> +import traceback
The directory name should `service` too...

2019-11-07 18:27 UTC, ahab94 commented on db/client.py
> +class ClientImplementation(object):
This should Just be `MongoClient`... as we already know that it's an implementation no need to specify.

2019-11-07 18:28 UTC, ahab94 commented on db/client.py
> +    def __init__(self, conn):
This is a constructor... here we should get username, password, host... and initiate connection here.
that would be used in all the queries.

2019-11-07 18:29 UTC, ahab94 commented on db/client.py
> +                username == "ronaldo"
Where are we comparing this username password? What is being achieved here?

2019-11-07 18:29 UTC, ahab94 commented on db/client.py
> +            # new_client()
Let's remove the comment.

2019-11-07 18:29 UTC, ahab94 commented on db/client.py
> +                auth.role = "student"
Why is role hardcoded here?

2019-11-07 18:31 UTC, ahab94 commented on models/models.py
> +def new_client():
We are not using this anymore right?

2019-11-07 18:33 UTC, ahab94 commented on models/models.py
> +    password = StringField()
Why is authmgr storing passwords in session information?

2019-11-07 18:35 UTC, ahab94 commented on service/service.py
> +
`service` itself should be a class. and in it's constructor taking in `client`. Which shouldn't be argument to in each function.. but something that's available to it as part of class's data.

2019-11-07 18:36 UTC, ahab94 commented on models/models.py
> +    password = StringField()
Password comparison would happen in `ApnaSchool` or any other service in question. AuthManager will only store sessions, validate, delete them.

2019-11-07 18:43 UTC, ahab94 commented on main/main.py
> +                new_client()
this is not being used anywhere right?

2019-11-11 11:31 UTC, merged